apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init-config
  namespace: mean-app
data:
  mongo-init.js: |
    db = db.getSiblingDB("meanStackExample"); // Selecciona la base de datos
    db.createUser({
      user: "appuser",
      pwd: "apppassword123",
      roles: [
        {
          role: "readWrite",
          db: "meanStackExample"
        }
      ]
    });
