apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init-config
  namespace: mean-app
data:
  mongo-init.js: |
    db = db.getSiblingDB(`${process.env.MONGO_INITDB_DATABASE}`); // Selecciona la base de datos
    db.createUser({
      user: `${process.env.MONGO_INITDB_ROOT_USERNAME}`,
      pwd: `${process.env.MONGO_INITDB_ROOT_PASSWORD}`,
      roles: [
        {
          role: "readWrite",
          db: `${process.env.MONGO_INITDB_DATABASE}`
        }
      ]
    });
