---
apiVersion: v1
kind: Service
metadata:
  name: mean-backend-service
  namespace: mean-app
spec:
  selector:
    app: mean-backend
  ports:
    - protocol: TCP
      port: 5200
      targetPort: 5200