---
apiVersion: v1
kind: Service
metadata:
  name: mean-frontend-service
  namespace: mean-app
spec:
  type: LoadBalancer
  selector:
    app: mean-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
