apiVersion: apps/v1
kind: Deployment
metadata:
  name: mean-backend
  namespace: mean-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mean-backend
  template:
    metadata:
      labels:
        app: mean-backend
    spec:
      containers:
      - name: backend
        image: mikeangeloo/backend-app:v1.0.0
        ports:
        - containerPort: 5200
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DB_PASSWORD
        - name: DB_HOST
          value: mongodb.mean-app.svc.cluster.local
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DB_NAME
