apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: mean-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_USER
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_PASSWORD
          volumeMounts:
            - name: mongo-init-volume
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mongo-init-volume
          configMap:
            name: mongo-init-config
